DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   username TEXT UNIQUE NOT NULL,
   password TEXT NOT NULL
);

CREATE TABLE submission (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   fieldname TEXT NOT NULL,
   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   source BLOB NOT NULL,
   status TEXT NOT NULL,
   length INTEGER NOT NULL,
   user_id INTEGER NOT NULL,
   FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE result (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   lang TEXT NOT NULL,
   stdin BLOB NOT NULL,
   stdout BLOB NOT NULL,
   stderr BLOB NOT NULL,
   exitcode INTEGER NOT NULL,
   user_id INTEGER NOT NULL,
   submission_id INTEGER NOT NULL,
   FOREIGN KEY (user_id) REFERENCES user (id),
   FOREIGN KEY (submission_id) REFERENCES submission (id)
);
