DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   username TEXT UNIQUE NOT NULL,
   password TEXT NOT NULL
);

CREATE TABLE field (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   fieldname TEXT NOT NULL,
   fieldlang TEXT NOT NULL
);

CREATE TABLE submission (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   field_id INTEGER NOT NULL,
   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   source TEXT NOT NULL,
   stdout TEXT NOT NULL,
   stderr TEXT NOT NULL,
   status TEXT NOT NULL,
   length INTEGER NOT NULL,
   user_id INTEGER NOT NULL,
   FOREIGN KEY (user_id) REFERENCES user (id)
   FOREIGN KEY (field_id) REFERENCES field (id)
);
